/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import MembrosClube.Associado;
import MembrosClube.Funcionario;
import conexao.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Higor Senna
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form LoginAtendente
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inicioCB1 = new javax.swing.JCheckBox();
        jlogin = new javax.swing.JTextField();
        jBotaoEntrar = new javax.swing.JButton();
        inicioCB2 = new javax.swing.JCheckBox();
        jBotaoLimpar = new javax.swing.JButton();
        jsenha = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Dialog", 0, 40)); // NOI18N
        label1.setText("\t\t\t       BEM VINDO AO CLUBE!");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Senha");

        inicioCB1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inicioCB1.setText("Atendente");

        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });

        jBotaoEntrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBotaoEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/imagens/homehost_ok.png"))); // NOI18N
        jBotaoEntrar.setText("Entrar");
        jBotaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoEntrarActionPerformed(evt);
            }
        });

        inicioCB2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inicioCB2.setText("Associado");

        jBotaoLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBotaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/imagens/x.png"))); // NOI18N
        jBotaoLimpar.setText("Limpar");
        jBotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoLimparActionPerformed(evt);
            }
        });

        jsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jBotaoLimpar)
                .addGap(40, 40, 40)
                .addComponent(jBotaoEntrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inicioCB1)
                        .addGap(59, 59, 59)
                        .addComponent(inicioCB2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicioCB1)
                    .addComponent(inicioCB2))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoEntrar)
                    .addComponent(jBotaoLimpar))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jloginActionPerformed

    private void jBotaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoLimparActionPerformed
       jlogin.setText(null);
       jsenha.setText(null);
       inicioCB1.setSelected(false); //atendente
       inicioCB2.setSelected(false); //associado
    }//GEN-LAST:event_jBotaoLimparActionPerformed

    private void jBotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoEntrarActionPerformed
       if(jlogin.getText().equals("") || jsenha.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Preencha os campos!");
       }
       else if(inicioCB1.isSelected() || inicioCB2.isSelected()){
           if(inicioCB1.isSelected() && inicioCB2.isSelected()){
               JOptionPane.showMessageDialog(this,"Selecione Apenas um campo!");
               inicioCB1.setSelected(false);
               inicioCB2.setSelected(false);
                jlogin.setText(null);
                jsenha.setText(null);
                jlogin.requestFocus();               
               
           }else if(inicioCB1.isSelected()){
                  Funcionario f = new Funcionario();
                try {
                    f.consultaFuncs(jlogin.getText(),jsenha.getText());
                    if(f.consultaFuncs(jlogin.getText(),jsenha.getText()) == true ){
                        JOptionPane.showMessageDialog(this, "Conectou");
                        TelaAtendente tela = new TelaAtendente(this, true);
                        tela.setVisible(true);
                    }
                    else{
                       JOptionPane.showMessageDialog(this, "Login ou senha Incorretos");
                       jlogin.setText("");
                       jsenha.setText("");
                       inicioCB1.setSelected(false);
                       inicioCB2.setSelected(false);
                       jlogin.requestFocus();
                    }
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "class,Consulte o desenvolvedor " + ex.getMessage());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "sql,Consulte o desenvolvedor " +ex.getMessage());
                }  
           }
           else if(inicioCB2.isSelected()){
              Associado as = new Associado();
           }          
       }  
       else{
           JOptionPane.showMessageDialog(this,"Selecione um campo!");
       }
        
       
        
    }//GEN-LAST:event_jBotaoEntrarActionPerformed

    private void jsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox inicioCB1;
    private javax.swing.JCheckBox inicioCB2;
    private javax.swing.JButton jBotaoEntrar;
    private javax.swing.JButton jBotaoLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jlogin;
    private javax.swing.JTextField jsenha;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
