/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.funcionarios;

import DaoClasses.ClassesProjeto.FuncionarioDao;
import MembrosClube.Funcionario;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Higor Senna
 */
public class TelaShowFunc extends javax.swing.JDialog {
    
    /**
     * Creates new form TelaShowFunc
     */
    public TelaShowFunc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jAlterarFunc = new javax.swing.JButton();
        jRemoverFunc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Login", "Senha"
            }
        ));
        jScrollPane1.setViewportView(jTabela);

        jAlterarFunc.setText("Alterar");
        jAlterarFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jAlterarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarFuncActionPerformed(evt);
            }
        });

        jRemoverFunc.setText("Remover");
        jRemoverFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRemoverFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoverFuncActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exibição de Funcionários");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jAlterarFunc)
                        .addGap(18, 18, 18)
                        .addComponent(jRemoverFunc)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRemoverFunc)
                    .addComponent(jAlterarFunc)
                    .addComponent(jButton1))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try {        

            //preencher a grid
            ArrayList<Funcionario> listaF = new FuncionarioDao().buscarTodos();

            preencheGrid(listaF);

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Contate o Desenvolvedor");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Contate o Desenvolvedor " + ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jRemoverFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoverFuncActionPerformed
       if (jTabela.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Funcionário");
        } else {
            if (JOptionPane.showConfirmDialog(this, "Deseja Apagar o  Funcionário "
                    + jTabela.getValueAt(jTabela.getSelectedRow(), 1) + "?", "Apagar",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                Funcionario f = new Funcionario();
                f.setId(Integer.parseInt(jTabela.getValueAt(jTabela.getSelectedRow(), 0).toString()));

                try {

                    new FuncionarioDao().deletar(f);       
                      //preencher a grid
                    ArrayList<Funcionario> listaF = new FuncionarioDao().buscarTodos();
                    listaF.removeAll(listaF);
                    preencheGrid(listaF);
                   

                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "Contate o Desenvolvedor");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Contate o Desenvolvedor " + ex.getMessage());
                }
               

            }
        }
    }//GEN-LAST:event_jRemoverFuncActionPerformed

    private void jAlterarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarFuncActionPerformed
        if (jTabela.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Remédio");
        } else {
            
            try {
                int codFunc = Integer.parseInt(jTabela.getValueAt(jTabela.getSelectedRow(), 0).toString() );
                
                Funcionario func = new FuncionarioDao().buscarPelaChave(codFunc);
                
               TelaCadFunc tcf = new TelaCadFunc(null, true);
                
                tcf.preencheTela(func);
                
                tcf.setVisible(true);
                
                ArrayList<Funcionario> listaF = new FuncionarioDao().buscarTodos();
                preencheGrid(listaF);
                
            } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "Contato o Desenvolvedor");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Contato o Desenvolvedor " + ex.getMessage());
                }
            
        }
    }//GEN-LAST:event_jAlterarFuncActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void preencheGrid(ArrayList<Funcionario> listaF) {
        DefaultTableModel table = (DefaultTableModel) jTabela.getModel(); /*DfaultTableModel 
        utilizado para nao ter que escrever toda hora jTabela.getModel().removeRow,
        jTabela.getModel().addRow(linha) etc*/

        for (int i = 0; i < table.getRowCount(); i++) {
            table.removeRow(i);
        }

        for (Funcionario func : listaF) {
            String[] linha = {func.getId() + "",
                func.getNome(),
                func.getLogin(),
                func.getSenha()};
            table.addRow(linha);
        }        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaShowFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaShowFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaShowFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaShowFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaShowFunc dialog = new TelaShowFunc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAlterarFunc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jRemoverFunc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables
   

}

